apiVersion: apps/v1
kind: Deployment
metadata:
  name: dummy-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dummy-app
  template:
    metadata:
      labels:
        app: dummy-app
    spec:
      containers:
      - name: dummy-app
        image: ghcr.io/jerryctt/dummy-golang-app:418d74c866538e67f46cdec7808d4d7deabe812a
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: dummy-service
spec:
  selector:
    app: dummy-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
